#!/usr/bin/env python3
"""
micro_audio.py - the sound under each badge. Synthesised, never sampled.

A pop off a sample library arrives with a room on it, and five of them in eight
seconds start sounding like five different rooms. So it is generated, and since
7 September 2026 it is generated by `engine/impact.py`, which is what Exercise's
hits were always made of:

    click     1.2 ms of noise, differenced       the contact
    body      sine falling 1.0 -> 0.42 of f0     the landing
    sub       an octave under it, 90 ms          the weight behind it
    air       band-passed noise, 35 ms           the spray after it

Micro's own version had no sub, ran off a 760 Hz root and dropped its pitch by
2.4 in 45 ms; the engine's drops by three in 30 and sits an octave lower. The
measured difference was -20.6 LUFS against -19.4, and the smaller number is not
the point - a badge landing on a row is the same event as a muscle lighting up,
and it should not sound like a bubble in one variant and an impact in the other.

**The synthesis is not copied in here.** `impact.strike` and `impact.build` are
the engine's, and this file is what is Micro's own: reading the cues
`flowanim.py` wrote, grouping them back into rows, and writing the wav.

The note still rises through the clip. Row 1 lands on the root and rows 2-5 climb
a major pentatonic, and the badges inside a row step up two semitones each - that
is `impact.SCALE` and `impact.STEP`, shared rather than kept twice. Five
identical thuds read as a machine; five rising ones read as a list being counted
off, and a viewer waits for the next one. That wait is the whole point.

    python3 micro_audio.py --cues 1,1.09,1.18,2,... -o pops.wav
    python3 micro_audio.py --cues-file liver_cues.txt -o pops.wav
"""
import argparse
import os
import sys
import wave

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "engine"))
import impact                                        # noqa: E402

SR = impact.SR
ROOT = 420.0                     # the engine's, and Exercise's. Was 760 here


def write_wav(path, x, sr=SR):
    d = (np.clip(x, -1, 1) * 32767).astype("<i2")
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        w.writeframes(d.tobytes())


def act_two(cues, flip_seconds, seconds, root=ROOT, gain=0.45):
    """Everything after the turn, as one buffer starting at the flip's first frame.

    **It is the same strike act one's badges land on, not a bell.** The first cut
    used `impact.bell` on the reasoning that nothing hits anything behind glass -
    a row of type fades up, an arc sweeps - and the user rejected it against the
    other variant: one clip may not change instrument halfway through. So act two
    is `impact.strike`, the engine's own hit, at about half act one's level and
    climbing the same `impact.SCALE`. The card is the continuation of the count,
    and it should sound like the same hand.

    Times in the cue file are act two's own; the flip sits in front of them, so
    everything is offset by `flip_seconds` here and nowhere else.
    """
    n = int(round((flip_seconds + seconds) * SR)) + SR
    buf = np.zeros(n, dtype=np.float64)

    def place(x, t):
        i = int(round(t * SR))
        if i < 0:
            x, i = x[-i:], 0
        j = min(len(buf), i + len(x))
        if j > i:
            buf[i:j] += x[:j - i]

    # THE TURN ITSELF, which had no sound at all until now: the card moved and
    # the mix simply went quiet under it, so the join read as a gap. Two engine
    # parts, both already in this clip's vocabulary:
    #
    #   the riser LEADS the turn - it has to be arriving as the card starts to
    #   move, so it is placed to END on the last frame of the flip rather than to
    #   start on the first. Same gesture act one's finale uses.
    #   the card LANDS on the half-turn, where the back face comes round: one
    #   low strike at 96 Hz, which is the badge hit an octave and a half under
    #   itself and reads as weight rather than as another badge.
    r = impact.riser(dur=max(0.18, flip_seconds * 0.8))
    place(r * 0.55, max(0.0, flip_seconds - len(r) / SR))
    place(impact.strike(96.0, dur=0.42) * 0.55, flip_seconds * 0.52)

    for k, t in enumerate(cues["rows"]):
        semis = impact.SCALE[k % len(impact.SCALE)] + 12 * (k // len(impact.SCALE))
        place(impact.strike(root * 2 ** (semis / 12.0), dur=0.34) * gain,
              flip_seconds + t)

    # The ring's sweep: a quiet rise under the arcs, ending as they do. Not
    # impact.riser, which is 0.26s and belongs to act one's finale - this is 1.3s
    # of the same idea, and it lives here because no other variant fills a ring.
    dur = cues.get("ring_dur", 1.3)
    t = np.linspace(0, dur, int(dur * SR), endpoint=False)
    f = root * 0.5 * (1 + 1.4 * (t / dur) ** 1.7)
    env = np.sin(np.pi * (t / dur) ** 0.8) ** 1.4
    # 0.45, and this is the ceiling for this sound rather than a step towards
    # more. At 0.45 the sweep's RMS equals the chord's ONSET RMS: it still reads
    # as a landing because the chord's peak is 12 dB above it and a transient is
    # what the ear takes as an arrival, but there is nothing left over. If it is
    # asked for louder again, both go up together by the same amount so the
    # landing keeps its margin - and `impact.finale` enters at the engine's own
    # gain, so that means a multiplier here, measured against ACT ONE's chord as
    # well, which is the same buffer and must not drift from this one.
    #
    # 0.36 was the step before, and 0.12 before that. At 0.12 the fill measured -34.8 dB
    # against -25.0 for the row ticks and -26.7 for the closing chord: the one
    # sound in act two that runs UNDER a number counting was the quietest thing
    # in it, and the user's words were "jako jako tiho". +9.6 dB puts it just
    # above a tick and just under the chord.
    #
    # Under the chord is the constraint, and it is checked at the chord's ONSET
    # or its PEAK, never at an RMS window over its length. The chord is a strike
    # that decays and the sweep is flat, so a 1.2s average punishes the chord for
    # its own tail: by that number the sweep passed the chord at 0.36 while the
    # landing was still 3 dB over it where it is actually heard. Measure the
    # first 0.3s, or measure peaks. The same shape as the badge windows in
    # render.sh - the window held more than the thing being tested.
    place(0.45 * gain * env * np.sin(2 * np.pi * np.cumsum(f) / SR),
          flip_seconds + cues["ring"])

    # THE ENDING IS ACT ONE'S CHORD, and it lands when the number stops moving.
    #
    # Not a bell and not a strike: `impact.finale` is what act one already closes
    # on, so the clip ends on the sound it has ended on once already. Macro made
    # the same move and for the same reason - the user picked it knowing it
    # repeats. It goes in at the engine's own gain and render.sh mixes act two at
    # unity: the level impact.py returns is the level it has to arrive at, which
    # is the whole reason the riser is not summed into the pops.
    #
    # Generated in its own 2.6s buffer and PLACED, rather than asked for at an
    # offset inside a buffer of act two's length - `finale` returns an array of
    # `seconds`, so adding them directly is a shape mismatch waiting to happen.
    #
    # The instant is where the count finishes, not where it starts: the number
    # rolls from 0 to the score over `ring_dur`, and a chord under a number still
    # moving reads as landing early.
    # `land` is where the number last visibly changes, which is 0.34s before the
    # count nominally ends: the ease-out crawls the final half percent with
    # nothing moving. The chord goes on the visible instant, not the arithmetic
    # one - the same distinction as a badge's cue against its arrival.
    land = cues.get("land", cues["score"] + cues.get("ring_dur", 1.3))
    place(impact.finale(0.0, 2.6, root=root), flip_seconds + land)

    # Deliberately NOT normalised. Act one's pops are, because they are fifteen
    # of one sound and the peak is arbitrary; this buffer ends on impact.finale,
    # and scaling the buffer to fit a peak would move the chord off the level the
    # engine hands it over at - the exact fault that put one number in impact.py
    # into the mix at three different levels. If it clips, lower `gain`, which is
    # the rows, not the chord.
    pk = np.abs(buf).max()
    if pk > 0.99:
        print(f"  act two peaks at {pk:.3f} - lower gain rather than normalising")
    return buf[:int(round((flip_seconds + seconds) * SR))]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--cues", help="comma separated seconds")
    p.add_argument("--cues-file", help="the file flowanim.py --micro-cues wrote")
    p.add_argument("--times", default="1,2,4,5.5,7", help="row times, if no cues given")
    p.add_argument("--counts", default="3,3,3,3,3", help="badges per row, if no cues given")
    p.add_argument("--stagger", type=float, default=0.09)
    p.add_argument("--seconds", type=float, default=8.0)
    p.add_argument("--root", type=float, default=ROOT, help="row 1's note, in Hz")
    p.add_argument("--finale-file", help="the file flowanim.py --finale-cue wrote: one "
                                         "instant, and the riser is laid on it")
    p.add_argument("--finale-gain", type=float, default=None,
                   help="override impact.finale's own level. Nothing is passed unless "
                        "this is given: the engine's default is the level the finale "
                        "was auditioned and chosen at, and two variants tuning the "
                        "same shared sound separately is how it ends up at two levels")
    p.add_argument("--finale-out", help="where the riser is written. It gets its own "
                                        "wav rather than being summed into the pops, "
                                        "because the caller applies a badge gain to "
                                        "that file and the riser is not a badge. "
                                        "Defaults to <out>_riser.wav")
    p.add_argument("--gain", type=float, default=0.72)
    # Not required: with --act2-cues alone this file writes act two and
    # nothing else, and demanding an act-one path it will not use meant
    # render2.sh had to recompute the badge pops into /dev/null to get a
    # card wav out of it.
    p.add_argument("-o", "--out")
    # Act two. Its own cue file, its own wav, and it is not mixed into the pops:
    # a badge gain belongs to badges (see the note below the riser), and the card
    # is a different level entirely.
    p.add_argument("--act2-cues", help="the json micro_card.py's Plan wrote")
    p.add_argument("--act2-seconds", type=float)
    p.add_argument("--flip-seconds", type=float, default=0.0,
                   help="the turn, which sits between the two acts")
    p.add_argument("--act2-out", help="everything from the first frame of the turn")
    args = p.parse_args()

    if args.act2_cues:
        import json
        c = json.load(open(args.act2_cues))
        secs = args.act2_seconds or c.get("seconds", 7.0)
        x = act_two(c, args.flip_seconds, secs, root=args.root)
        out = args.act2_out or "act2.wav"
        write_wav(out, x)
        print(f"  act two: {len(c['rows'])} rows, ring at {c['ring']:.2f}s, "
              f"{args.flip_seconds + secs:.2f}s -> {out}")
        if not (args.cues or args.cues_file):
            return

    if not args.out:
        raise SystemExit("-o is required for the badge pops")
    if args.cues_file:
        args.cues = open(args.cues_file).read().strip()
    if args.cues:
        cues = sorted(float(c) for c in args.cues.split(","))
        # Regroup by row so the notes still climb: cues that share a landing
        # window belong to the same row.
        per_row, row, j, last = [], 0, 0, None
        for t in cues:
            if last is not None and t - last > args.stagger * 2.5:
                row, j = row + 1, 0
            per_row.append((row, j))
            j += 1
            last = t
    else:
        times = [float(t) for t in args.times.split(",")]
        counts = [int(c) for c in args.counts.split(",")]
        cues, per_row = [], []
        for r, (t0, n) in enumerate(zip(times, counts)):
            for j in range(n):
                cues.append(t0 + j * args.stagger)
                per_row.append((r, j))

    x = impact.build(cues, args.seconds, per_row, root=args.root, gain=args.gain)

    # The riser is not one of these cues, and never was: they are regrouped into
    # rows by the gaps between them, so a finale appended to the list would open a
    # sixth row - SCALE[5 % 5] is the root again - and the cadence that answers the
    # count would be sounded as one more badge landing. Since it is not a badge it
    # does not travel with them either; see below.
    pk = np.abs(x).max()
    if pk > 0.97:
        x *= 0.97 / pk
    write_wav(args.out, x)

    # The riser does not go into this wav. It used to, and the caller then applied
    # POP_GAIN to the file - 0.85 here, 0.62 in Exercise, 0.80 in Biohacks - so one
    # number in impact.py arrived at three different levels, none of them the level
    # the user picked the sound at. A badge gain belongs to badges. It goes out on
    # its own so the mixer can take it at unity, which is the contract impact.py
    # states: the level it returns is the level it has to arrive at.
    fin = None
    if args.finale_file and os.path.exists(args.finale_file):
        fin = float(open(args.finale_file).read().strip())
        # No gain unless asked for. This file used to force one, tuned against the
        # chord impact.finale made before 176c632; the sound is an FM bell now and
        # the old number lands 8.1 dB over the level it was chosen at. Level is a
        # property of a sound the variants share, so it is the engine's to hold.
        kw = {} if args.finale_gain is None else {"gain": args.finale_gain}
        r = impact.finale(fin, args.seconds, root=args.root, **kw)
        fout = args.finale_out or os.path.splitext(args.out)[0] + "_riser.wav"
        write_wav(fout, r)

    tail = f" + a riser at {fin:.2f}s -> {fout}" if fin is not None else ""
    print(f"  {len(cues)} hits over {args.seconds}s at root {args.root:.0f} Hz"
          f" -> {args.out}{tail}")


if __name__ == "__main__":
    main()
