#!/usr/bin/env python3
"""
micro_audio.py - the sound under each badge. Synthesised, never sampled.

A pop off a sample library arrives with a room on it, and five of them in eight
seconds start sounding like five different rooms. So it is generated, and since
7 September 2026 it is generated by `engine/impact.py`, which is what Exercise's
hits were always made of:

    click     1.2 ms of noise, differenced       the contact
    body      sine falling 1.0 -> 0.42 of f0     the landing
    sub       an octave under it, 90 ms          the weight behind it
    air       band-passed noise, 35 ms           the spray after it

Micro's own version had no sub, ran off a 760 Hz root and dropped its pitch by
2.4 in 45 ms; the engine's drops by three in 30 and sits an octave lower. The
measured difference was -20.6 LUFS against -19.4, and the smaller number is not
the point - a badge landing on a row is the same event as a muscle lighting up,
and it should not sound like a bubble in one variant and an impact in the other.

**The synthesis is not copied in here.** `impact.strike` and `impact.build` are
the engine's, and this file is what is Micro's own: reading the cues
`flowanim.py` wrote, grouping them back into rows, and writing the wav.

The note still rises through the clip. Row 1 lands on the root and rows 2-5 climb
a major pentatonic, and the badges inside a row step up two semitones each - that
is `impact.SCALE` and `impact.STEP`, shared rather than kept twice. Five
identical thuds read as a machine; five rising ones read as a list being counted
off, and a viewer waits for the next one. That wait is the whole point.

    python3 micro_audio.py --cues 1,1.09,1.18,2,... -o pops.wav
    python3 micro_audio.py --cues-file liver_cues.txt -o pops.wav
"""
import argparse
import os
import sys
import wave

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "engine"))
import impact                                        # noqa: E402

SR = impact.SR
ROOT = 420.0                     # the engine's, and Exercise's. Was 760 here


def write_wav(path, x, sr=SR):
    d = (np.clip(x, -1, 1) * 32767).astype("<i2")
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        w.writeframes(d.tobytes())


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--cues", help="comma separated seconds")
    p.add_argument("--cues-file", help="the file flowanim.py --micro-cues wrote")
    p.add_argument("--times", default="1,2,4,5.5,7", help="row times, if no cues given")
    p.add_argument("--counts", default="3,3,3,3,3", help="badges per row, if no cues given")
    p.add_argument("--stagger", type=float, default=0.09)
    p.add_argument("--seconds", type=float, default=8.0)
    p.add_argument("--root", type=float, default=ROOT, help="row 1's note, in Hz")
    p.add_argument("--gain", type=float, default=0.72)
    p.add_argument("-o", "--out", required=True)
    args = p.parse_args()

    if args.cues_file:
        args.cues = open(args.cues_file).read().strip()
    if args.cues:
        cues = sorted(float(c) for c in args.cues.split(","))
        # Regroup by row so the notes still climb: cues that share a landing
        # window belong to the same row.
        per_row, row, j, last = [], 0, 0, None
        for t in cues:
            if last is not None and t - last > args.stagger * 2.5:
                row, j = row + 1, 0
            per_row.append((row, j))
            j += 1
            last = t
    else:
        times = [float(t) for t in args.times.split(",")]
        counts = [int(c) for c in args.counts.split(",")]
        cues, per_row = [], []
        for r, (t0, n) in enumerate(zip(times, counts)):
            for j in range(n):
                cues.append(t0 + j * args.stagger)
                per_row.append((r, j))

    x = impact.build(cues, args.seconds, per_row, root=args.root, gain=args.gain)
    write_wav(args.out, x)
    print(f"  {len(cues)} hits over {args.seconds}s at root {args.root:.0f} Hz -> {args.out}")


if __name__ == "__main__":
    main()
